version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: CRM-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'

  postgres:
    image: bitnami/postgresql
    container_name: CRM-Postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_crm
